### ISSUE TITLE
wash exits with SIGSEGV panic when listing s3 buckets 

### ISSUE THREAD

**Issue by timidri** [puppetlabs/wash#167]
**Describe the bug**
After issuing an `ls` command in an s3 directory and receiving a list, wash exits with a panic message.

**To Reproduce**
1. Create a profile pointing to the TSE AWS account and call it 'tse'
2. Run command 'wash server ~/wash_mnt --loglevel trace`
3. `cd ~/wash_mnt/aws/tse/resources/s3`
4. ls

**Expected behavior**
A list of available s3 buckets and wash continuing to operate normally

**Logs**

Famous last words:
```
DEBU[2019-03-25T12:35:53+01:00] FUSE: Prefetching children of /aws/default/resources/s3/pe28-scaleguide complete: <nil>
TRAC[2019-03-25T12:35:53+01:00] Cache hit on 92894-ls
DEBU[2019-03-25T12:35:53+01:00] Cache miss on List::/aws/default/resources/s3/supportapj
DEBU[2019-03-25T12:35:53+01:00] FUSE: Prefetching children of /aws/default/resources/s3/tseteam complete: <nil>
TRAC[2019-03-25T12:35:53+01:00] Cache hit on 92894-ls
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x134f13e]

goroutine 885 [running]:
github.com/puppetlabs/wash/plugin.CachedList.func1(0x263879c, 0x10, 0xc005940d68, 0x1)
	/Users/dimitri.tischenko/git/wash/plugin/cache.go:118 +0x12e
github.com/puppetlabs/wash/datastore.(*MemCache).GetOrUpdate(0xc000373110, 0xc0056ea140, 0x31, 0x37e11d600, 0x0, 0xc000372ff0, 0x0, 0x0, 0x0, 0x0)
	/Users/dimitri.tischenko/git/wash/datastore/cache.go:80 +0x330
github.com/puppetlabs/wash/plugin.cachedOp(0x262d598, 0x4, 0x284f980, 0xc0003cc2a0, 0x37e11d600, 0xc000372ff0, 0xc005a2fe78, 0x100b8e8, 0x24463c0, 0x254b800)
	/Users/dimitri.tischenko/git/wash/plugin/cache.go:189 +0x16f
github.com/puppetlabs/wash/plugin.cachedActionOp(0x2446300, 0x284f980, 0xc0003cc2a0, 0xc000372ff0, 0xc0003cc2a0, 0x2458100, 0x254b800, 0x0)
	/Users/dimitri.tischenko/git/wash/plugin/cache.go:166 +0xb3
github.com/puppetlabs/wash/plugin.CachedList(0x284e000, 0xc000372fc0, 0xb93d148, 0xc0003cc2a0, 0xc0003cc2a0, 0xc0003cc2a0, 0xc000372f01, 0x22a67e0, 0x2822e20)
	/Users/dimitri.tischenko/git/wash/plugin/cache.go:111 +0xc4
github.com/puppetlabs/wash/fuse.(*dir).children(0xc000324440, 0x284e000, 0xc000372fc0, 0x2822e20, 0x22aa0e0, 0xc00040e190, 0x284e000, 0xc000372fc0)
	/Users/dimitri.tischenko/git/wash/fuse/dir.go:55 +0xcb
github.com/puppetlabs/wash/fuse.(*dir).Lookup.func1(0xc000324440, 0xc000d17990, 0x8, 0xc000169450)
	/Users/dimitri.tischenko/git/wash/fuse/dir.go:82 +0xcf
created by github.com/puppetlabs/wash/fuse.(*dir).Lookup
	/Users/dimitri.tischenko/git/wash/fuse/dir.go:81 +0x89f
```

Full log: https://gist.github.com/timidri/6c8a3e05aa159a7034a9abaf1aae8fcb

**Environment (please complete the following information):**
 - OS: [macOS 10.14.3]
 - Version/Build number [7c092cfd67d742efba671076f620f8f7eda9eece]
 - Cloud target [AWS]

**Comment by ekinanp** [comment]
This is fixed in https://github.com/puppetlabs/wash/pull/166 -- reason it's happening is b/c of https://github.com/puppetlabs/wash/blob/master/plugin/aws/s3Bucket.go#L52, the array is left with gaps that default to a nil entry.
